dubbo:
  application:
    name: town-test-provider
    logger: slf4j
  protocol:
    name: dubbo
    port: 40001
  registry:
    address: nacos://${nacos.address:127.0.0.1}:8848?username=nacos&password=123456
    group: town-test