dubbo:
  application:
    name: town-question-provider
    logger: slf4j
    check-serializable: false
    serialize-check-status: WARN
    register-mode: instance
  metadata-report:
    address: nacos://${nacos.address:127.0.0.1}:8848
  protocol:
    name: dubbo
    port: 40005
  registry:
    address: nacos://${nacos.address:127.0.0.1}:8848?username=nacos&password=123456
    group: town-test