spring:
  datasource:
    url: jdbc:mysql://localhost:13306/town?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: "123456"          # 没有密码留空即可
      database: 0

mybatis:
  configuration:
    map-underscore-to-camel-case: true

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql


dubbo:
  application:
    name: town-dao-provider
    logger: slf4j
    check-serializable: false
    serialize-check-status: WARN
  protocol:
    name: dubbo
    port: 40002
  registry:
    address: nacos://${nacos.address:127.0.0.1}:8848?username=nacos&password=123456
    group: town-test