dubbo:
  metadata-report:
    address: nacos://${nacos.address:127.0.0.1}:8848
  application:
    name: town-center-consumer
    logger: slf4j
    qos-port: 44444
    check-serializable: false
    serialize-check-status: WARN
    register-mode: interface
  registry:
    address: nacos://${nacos.address:127.0.0.1}:8848?username=nacos&password=123456&register-consumer-url=false
    group: town-test
    register-mode: interface
  consumer:
    check: false

# netty 配置
netty:
  # boss线程数量
  boss: 4
  # worker线程数量
  worker: 2
  # 连接超时时间
  timeout: 6000
  # 服务器主端口
  port: 18023
  # 服务器备用端口
  portSalve: 18026
  # 服务器地址
  host: 127.0.0.1
